services:
  - type: web
    name: cadencea-backend
    env: python
    plan: free

    rootDir: backend

    buildCommand: |
      pip install -r requirements.txt

    startCommand: |
      gunicorn project.wsgi:application

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: project.settings

    aptPackages:
      - ffmpeg
